-- Terminal Dark colorscheme for Neovim
-- Self-contained, no plugin dependency

vim.cmd("highlight clear")
if vim.g.syntax_on then
  vim.cmd("syntax reset")
end

vim.o.termguicolors = true
vim.g.colors_name = "terminal"

local c = {
  bg = "#0a0a0a",
  bg_alt = "#141414",
  bg_sel = "#333333",
  fg = "#e0e0e0",
  fg_dim = "#808080",
  fg_dark = "#555555",
  red = "#ff3333",
  green = "#00ff41",
  yellow = "#ffff00",
  blue = "#00ffff",
  purple = "#ff00ff",
  cyan = "#00ffff",
  orange = "#ff8800",
  white = "#ffffff",
}

local function hl(group, opts)
  vim.api.nvim_set_hl(0, group, opts)
end

-- Core UI
hl("Normal", { fg = c.fg, bg = c.bg })
hl("NormalNC", { fg = c.fg, bg = c.bg })
hl("NormalFloat", { fg = c.fg, bg = c.bg_alt })
hl("FloatBorder", { fg = c.fg_dark, bg = c.bg_alt })
hl("FloatTitle", { fg = c.green, bg = c.bg_alt, bold = true })
hl("ColorColumn", { bg = c.bg_alt })
hl("Conceal", { fg = c.fg_dark })
hl("Cursor", { fg = c.bg, bg = c.green })
hl("CursorIM", { fg = c.bg, bg = c.green })
hl("CursorColumn", { bg = c.bg_alt })
hl("CursorLine", { bg = c.bg_alt })
hl("CursorLineNr", { fg = c.green, bg = c.bg_alt })
hl("LineNr", { fg = c.fg_dark })
hl("LineNrAbove", { fg = c.fg_dark })
hl("LineNrBelow", { fg = c.fg_dark })
hl("SignColumn", { fg = c.fg_dim, bg = c.bg })
hl("FoldColumn", { fg = c.fg_dark, bg = c.bg })
hl("Folded", { fg = c.fg_dim, bg = c.bg_alt })
hl("StatusLine", { fg = c.fg, bg = c.bg_alt })
hl("StatusLineNC", { fg = c.fg_dim, bg = c.bg_alt })
hl("TabLine", { fg = c.fg_dim, bg = c.bg_alt })
hl("TabLineFill", { bg = c.bg_alt })
hl("TabLineSel", { fg = c.bg, bg = c.green, bold = true })
hl("WinBar", { fg = c.fg, bg = c.bg_alt })
hl("WinBarNC", { fg = c.fg_dim, bg = c.bg_alt })
hl("WinSeparator", { fg = c.bg_alt })
hl("VertSplit", { fg = c.bg_alt, bg = c.bg })
hl("Title", { fg = c.green, bold = true })
hl("Visual", { bg = c.bg_sel })
hl("VisualNOS", { bg = c.bg_sel })
hl("Search", { fg = c.bg, bg = c.yellow })
hl("IncSearch", { fg = c.bg, bg = c.green })
hl("CurSearch", { fg = c.bg, bg = c.green })
hl("Substitute", { fg = c.bg, bg = c.green })
hl("MatchParen", { fg = c.yellow, bg = c.bg_sel, bold = true })
hl("NonText", { fg = c.fg_dark })
hl("SpecialKey", { fg = c.fg_dark })
hl("Whitespace", { fg = c.fg_dark })
hl("EndOfBuffer", { fg = c.fg_dark })
hl("WildMenu", { fg = c.bg, bg = c.green })
hl("Directory", { fg = c.blue })
hl("Question", { fg = c.green })
hl("MoreMsg", { fg = c.green })
hl("ModeMsg", { fg = c.green })
hl("WarningMsg", { fg = c.yellow })
hl("ErrorMsg", { fg = c.red, bold = true })
hl("SpellBad", { sp = c.red, underline = true })
hl("SpellCap", { sp = c.yellow, underline = true })
hl("SpellRare", { sp = c.purple, underline = true })
hl("SpellLocal", { sp = c.cyan, underline = true })

-- Popup menu
hl("Pmenu", { fg = c.fg, bg = c.bg_alt })
hl("PmenuSel", { fg = c.bg, bg = c.green })
hl("PmenuKind", { fg = c.purple })
hl("PmenuKindSel", { fg = c.bg, bg = c.purple })
hl("PmenuExtra", { fg = c.fg_dim })
hl("PmenuExtraSel", { fg = c.bg, bg = c.fg_dim })
hl("PmenuSbar", { bg = c.bg_alt })
hl("PmenuThumb", { bg = c.fg_dim })

-- Standard syntax
hl("Comment", { fg = c.fg_dark, italic = true })
hl("Constant", { fg = c.orange })
hl("String", { fg = c.green })
hl("Character", { fg = c.green })
hl("Number", { fg = c.orange })
hl("Boolean", { fg = c.orange })
hl("Float", { fg = c.orange })
hl("Identifier", { fg = c.fg })
hl("Function", { fg = c.blue })
hl("Statement", { fg = c.purple })
hl("Conditional", { fg = c.purple })
hl("Repeat", { fg = c.purple })
hl("Label", { fg = c.purple })
hl("Operator", { fg = c.purple })
hl("Keyword", { fg = c.purple })
hl("Exception", { fg = c.purple })
hl("PreProc", { fg = c.yellow })
hl("Include", { fg = c.purple })
hl("Define", { fg = c.purple })
hl("Macro", { fg = c.purple })
hl("PreCondit", { fg = c.yellow })
hl("Type", { fg = c.yellow })
hl("StorageClass", { fg = c.yellow })
hl("Structure", { fg = c.yellow })
hl("Typedef", { fg = c.yellow })
hl("Special", { fg = c.cyan })
hl("SpecialChar", { fg = c.cyan })
hl("Tag", { fg = c.red })
hl("Delimiter", { fg = c.fg_dim })
hl("SpecialComment", { fg = c.fg_dim })
hl("Debug", { fg = c.red })
hl("Underlined", { fg = c.blue, underline = true })
hl("Error", { fg = c.red })
hl("Todo", { fg = c.yellow, bg = c.bg, bold = true })
hl("Ignore", { fg = c.fg_dark })

-- Diff
hl("DiffAdd", { fg = c.green, bg = c.bg })
hl("DiffChange", { fg = c.yellow, bg = c.bg })
hl("DiffDelete", { fg = c.red, bg = c.bg })
hl("DiffText", { fg = c.bg, bg = c.yellow })
hl("Added", { fg = c.green })
hl("Changed", { fg = c.yellow })
hl("Removed", { fg = c.red })

-- Diagnostics
hl("DiagnosticError", { fg = c.red })
hl("DiagnosticWarn", { fg = c.yellow })
hl("DiagnosticInfo", { fg = c.blue })
hl("DiagnosticHint", { fg = c.cyan })
hl("DiagnosticOk", { fg = c.green })
hl("DiagnosticUnderlineError", { sp = c.red, underline = true })
hl("DiagnosticUnderlineWarn", { sp = c.yellow, underline = true })
hl("DiagnosticUnderlineInfo", { sp = c.blue, underline = true })
hl("DiagnosticUnderlineHint", { sp = c.cyan, underline = true })
hl("DiagnosticUnderlineOk", { sp = c.green, underline = true })
hl("DiagnosticVirtualTextError", { fg = c.red, bg = c.bg_alt })
hl("DiagnosticVirtualTextWarn", { fg = c.yellow, bg = c.bg_alt })
hl("DiagnosticVirtualTextInfo", { fg = c.blue, bg = c.bg_alt })
hl("DiagnosticVirtualTextHint", { fg = c.cyan, bg = c.bg_alt })
hl("DiagnosticVirtualTextOk", { fg = c.green, bg = c.bg_alt })
hl("DiagnosticFloatingError", { fg = c.red })
hl("DiagnosticFloatingWarn", { fg = c.yellow })
hl("DiagnosticFloatingInfo", { fg = c.blue })
hl("DiagnosticFloatingHint", { fg = c.cyan })
hl("DiagnosticFloatingOk", { fg = c.green })
hl("DiagnosticSignError", { fg = c.red })
hl("DiagnosticSignWarn", { fg = c.yellow })
hl("DiagnosticSignInfo", { fg = c.blue })
hl("DiagnosticSignHint", { fg = c.cyan })
hl("DiagnosticSignOk", { fg = c.green })

-- TreeSitter
hl("@variable", { fg = c.fg })
hl("@variable.builtin", { fg = c.red })
hl("@variable.parameter", { fg = c.orange })
hl("@variable.member", { fg = c.fg })
hl("@constant", { fg = c.orange })
hl("@constant.builtin", { fg = c.orange })
hl("@constant.macro", { fg = c.orange })
hl("@module", { fg = c.yellow })
hl("@module.builtin", { fg = c.yellow })
hl("@label", { fg = c.purple })
hl("@string", { fg = c.green })
hl("@string.documentation", { fg = c.green })
hl("@string.regex", { fg = c.orange })
hl("@string.escape", { fg = c.cyan })
hl("@string.special", { fg = c.cyan })
hl("@string.special.symbol", { fg = c.cyan })
hl("@string.special.url", { fg = c.blue, underline = true })
hl("@character", { fg = c.green })
hl("@character.special", { fg = c.cyan })
hl("@boolean", { fg = c.orange })
hl("@number", { fg = c.orange })
hl("@number.float", { fg = c.orange })
hl("@type", { fg = c.yellow })
hl("@type.builtin", { fg = c.yellow })
hl("@type.definition", { fg = c.yellow })
hl("@attribute", { fg = c.yellow })
hl("@attribute.builtin", { fg = c.yellow })
hl("@property", { fg = c.cyan })
hl("@function", { fg = c.blue })
hl("@function.builtin", { fg = c.blue })
hl("@function.call", { fg = c.blue })
hl("@function.macro", { fg = c.blue })
hl("@function.method", { fg = c.blue })
hl("@function.method.call", { fg = c.blue })
hl("@constructor", { fg = c.yellow })
hl("@operator", { fg = c.purple })
hl("@keyword", { fg = c.purple })
hl("@keyword.coroutine", { fg = c.purple })
hl("@keyword.function", { fg = c.purple })
hl("@keyword.operator", { fg = c.purple })
hl("@keyword.import", { fg = c.purple })
hl("@keyword.type", { fg = c.purple })
hl("@keyword.modifier", { fg = c.purple })
hl("@keyword.repeat", { fg = c.purple })
hl("@keyword.return", { fg = c.purple })
hl("@keyword.debug", { fg = c.purple })
hl("@keyword.exception", { fg = c.purple })
hl("@keyword.conditional", { fg = c.purple })
hl("@keyword.conditional.ternary", { fg = c.purple })
hl("@keyword.directive", { fg = c.purple })
hl("@keyword.directive.define", { fg = c.purple })
hl("@punctuation.delimiter", { fg = c.fg_dim })
hl("@punctuation.bracket", { fg = c.fg_dim })
hl("@punctuation.special", { fg = c.cyan })
hl("@comment", { fg = c.fg_dark, italic = true })
hl("@comment.documentation", { fg = c.fg_dark, italic = true })
hl("@comment.error", { fg = c.red })
hl("@comment.warning", { fg = c.yellow })
hl("@comment.todo", { fg = c.yellow, bold = true })
hl("@comment.note", { fg = c.blue })
hl("@tag", { fg = c.red })
hl("@tag.builtin", { fg = c.red })
hl("@tag.attribute", { fg = c.orange })
hl("@tag.delimiter", { fg = c.fg_dim })
hl("@text", { fg = c.fg })
hl("@text.strong", { fg = c.fg, bold = true })
hl("@text.emphasis", { fg = c.fg, italic = true })
hl("@text.underline", { fg = c.fg, underline = true })
hl("@text.strike", { fg = c.fg, strikethrough = true })
hl("@text.title", { fg = c.green, bold = true })
hl("@text.literal", { fg = c.green })
hl("@text.uri", { fg = c.blue, underline = true })
hl("@text.reference", { fg = c.blue })
hl("@text.todo", { fg = c.yellow, bold = true })
hl("@text.warning", { fg = c.yellow })
hl("@text.error", { fg = c.red })
hl("@text.note", { fg = c.blue })
hl("@markup.heading", { fg = c.green, bold = true })
hl("@markup.italic", { fg = c.fg, italic = true })
hl("@markup.strong", { fg = c.fg, bold = true })
hl("@markup.strikethrough", { fg = c.fg, strikethrough = true })
hl("@markup.underline", { fg = c.fg, underline = true })
hl("@markup.quote", { fg = c.fg_dim, italic = true })
hl("@markup.math", { fg = c.green })
hl("@markup.link", { fg = c.blue, underline = true })
hl("@markup.link.label", { fg = c.blue })
hl("@markup.link.url", { fg = c.blue, underline = true })
hl("@markup.raw", { fg = c.green })
hl("@markup.list", { fg = c.purple })
hl("@markup.list.checked", { fg = c.green })
hl("@markup.list.unchecked", { fg = c.fg_dim })
hl("@diff.plus", { fg = c.green })
hl("@diff.minus", { fg = c.red })
hl("@diff.delta", { fg = c.yellow })

-- Git signs
hl("GitSignsAdd", { fg = c.green })
hl("GitSignsChange", { fg = c.yellow })
hl("GitSignsDelete", { fg = c.red })
hl("GitSignsAddNr", { fg = c.green })
hl("GitSignsChangeNr", { fg = c.yellow })
hl("GitSignsDeleteNr", { fg = c.red })
hl("GitSignsAddLn", { bg = c.bg_alt })
hl("GitSignsChangeLn", { bg = c.bg_alt })
hl("GitSignsDeleteLn", { bg = c.bg_alt })
hl("GitSignsCurrentLineBlame", { fg = c.fg_dark })

-- WhichKey
hl("WhichKey", { fg = c.green })
hl("WhichKeyGroup", { fg = c.blue })
hl("WhichKeySeparator", { fg = c.fg_dark })
hl("WhichKeyDesc", { fg = c.fg })
hl("WhichKeyValue", { fg = c.fg_dim })

-- Telescope
hl("TelescopeNormal", { fg = c.fg, bg = c.bg })
hl("TelescopeBorder", { fg = c.fg_dark, bg = c.bg })
hl("TelescopePromptNormal", { fg = c.fg, bg = c.bg_alt })
hl("TelescopePromptBorder", { fg = c.green, bg = c.bg_alt })
hl("TelescopePromptTitle", { fg = c.bg, bg = c.green, bold = true })
hl("TelescopePromptPrefix", { fg = c.green })
hl("TelescopePromptCounter", { fg = c.fg_dim })
hl("TelescopePreviewNormal", { fg = c.fg, bg = c.bg })
hl("TelescopePreviewBorder", { fg = c.blue, bg = c.bg })
hl("TelescopePreviewTitle", { fg = c.bg, bg = c.blue, bold = true })
hl("TelescopeResultsNormal", { fg = c.fg, bg = c.bg })
hl("TelescopeResultsBorder", { fg = c.purple, bg = c.bg })
hl("TelescopeResultsTitle", { fg = c.bg, bg = c.purple, bold = true })
hl("TelescopeSelection", { fg = c.fg, bg = c.bg_sel })
hl("TelescopeSelectionCaret", { fg = c.green })
hl("TelescopeMultiSelection", { fg = c.green, bg = c.bg_sel })
hl("TelescopeMatching", { fg = c.green, bold = true })

-- Neo-tree
hl("NeoTreeNormal", { fg = c.fg, bg = c.bg })
hl("NeoTreeNormalNC", { fg = c.fg_dim, bg = c.bg })
hl("NeoTreeDirectoryName", { fg = c.blue })
hl("NeoTreeDirectoryIcon", { fg = c.blue })
hl("NeoTreeFileName", { fg = c.fg })
hl("NeoTreeFileNameOpened", { fg = c.green })
hl("NeoTreeRootName", { fg = c.green, bold = true })
hl("NeoTreeGitAdded", { fg = c.green })
hl("NeoTreeGitModified", { fg = c.yellow })
hl("NeoTreeGitDeleted", { fg = c.red })
hl("NeoTreeGitIgnored", { fg = c.fg_dark })
hl("NeoTreeGitUntracked", { fg = c.green })
hl("NeoTreeGitConflict", { fg = c.red })
hl("NeoTreeIndentMarker", { fg = c.bg_alt })
hl("NeoTreeExpander", { fg = c.fg_dim })
hl("NeoTreeModified", { fg = c.yellow })
hl("NeoTreeWinSeparator", { fg = c.bg_alt, bg = c.bg })

-- Cmp
hl("CmpItemAbbr", { fg = c.fg })
hl("CmpItemAbbrDeprecated", { fg = c.fg_dim, strikethrough = true })
hl("CmpItemAbbrMatch", { fg = c.green, bold = true })
hl("CmpItemAbbrMatchFuzzy", { fg = c.green, bold = true })
hl("CmpItemKind", { fg = c.purple })
hl("CmpItemKindClass", { fg = c.yellow })
hl("CmpItemKindColor", { fg = c.red })
hl("CmpItemKindConstant", { fg = c.orange })
hl("CmpItemKindConstructor", { fg = c.yellow })
hl("CmpItemKindEnum", { fg = c.yellow })
hl("CmpItemKindEnumMember", { fg = c.orange })
hl("CmpItemKindEvent", { fg = c.purple })
hl("CmpItemKindField", { fg = c.cyan })
hl("CmpItemKindFile", { fg = c.blue })
hl("CmpItemKindFolder", { fg = c.blue })
hl("CmpItemKindFunction", { fg = c.blue })
hl("CmpItemKindInterface", { fg = c.yellow })
hl("CmpItemKindKeyword", { fg = c.purple })
hl("CmpItemKindMethod", { fg = c.blue })
hl("CmpItemKindModule", { fg = c.yellow })
hl("CmpItemKindOperator", { fg = c.purple })
hl("CmpItemKindProperty", { fg = c.cyan })
hl("CmpItemKindReference", { fg = c.red })
hl("CmpItemKindSnippet", { fg = c.green })
hl("CmpItemKindStruct", { fg = c.yellow })
hl("CmpItemKindText", { fg = c.fg })
hl("CmpItemKindTypeParameter", { fg = c.yellow })
hl("CmpItemKindUnit", { fg = c.orange })
hl("CmpItemKindValue", { fg = c.orange })
hl("CmpItemKindVariable", { fg = c.fg })
hl("CmpItemMenu", { fg = c.fg_dim })
hl("CmpItemMenuDefault", { fg = c.fg_dim })
hl("CmpGhostText", { fg = c.fg_dark })

-- LSP
hl("LspReferenceText", { bg = c.bg_sel })
hl("LspReferenceRead", { bg = c.bg_sel })
hl("LspReferenceWrite", { bg = c.bg_sel })
hl("LspSignatureActiveParameter", { fg = c.green, bold = true })
hl("LspCodeLens", { fg = c.fg_dim })
hl("LspCodeLensSeparator", { fg = c.fg_dark })
hl("LspInlayHint", { fg = c.fg_dim, bg = c.bg_alt })

-- Illuminate
hl("IlluminatedWordText", { bg = c.bg_sel })
hl("IlluminatedWordRead", { bg = c.bg_sel })
hl("IlluminatedWordWrite", { bg = c.bg_sel })

-- Indent blankline
hl("IblIndent", { fg = c.bg_alt })
hl("IblScope", { fg = c.fg_dark })
hl("IblWhitespace", { fg = c.bg_alt })

-- Buffer line
hl("BufferLineFill", { fg = c.fg_dim, bg = c.bg_alt })
hl("BufferLineBackground", { fg = c.fg_dim, bg = c.bg_alt })
hl("BufferLineBufferVisible", { fg = c.fg_dim, bg = c.bg_alt })
hl("BufferLineBufferSelected", { fg = c.fg, bg = c.bg, bold = true })
hl("BufferLineBufferSelectedIndicator", { fg = c.green, bg = c.bg })
hl("BufferLineIndicatorSelected", { fg = c.green, bg = c.bg })
hl("BufferLineCloseButton", { fg = c.fg_dim, bg = c.bg_alt })
hl("BufferLineCloseButtonVisible", { fg = c.fg_dim, bg = c.bg_alt })
hl("BufferLineCloseButtonSelected", { fg = c.fg, bg = c.bg })
hl("BufferLineModified", { fg = c.yellow, bg = c.bg_alt })
hl("BufferLineModifiedVisible", { fg = c.yellow, bg = c.bg_alt })
hl("BufferLineModifiedSelected", { fg = c.yellow, bg = c.bg })
hl("BufferLineSeparator", { fg = c.bg_alt, bg = c.bg_alt })
hl("BufferLineSeparatorVisible", { fg = c.bg_alt, bg = c.bg_alt })
hl("BufferLineSeparatorSelected", { fg = c.bg_alt, bg = c.bg })
hl("BufferLineTab", { fg = c.fg_dim, bg = c.bg_alt })
hl("BufferLineTabSelected", { fg = c.bg, bg = c.green, bold = true })
hl("BufferLineTabClose", { fg = c.fg_dim, bg = c.bg_alt })
hl("BufferLineTabSeparator", { fg = c.bg_alt, bg = c.bg_alt })
hl("BufferLineTabSeparatorSelected", { fg = c.bg_alt, bg = c.bg })
hl("BufferLineOffsetSeparator", { fg = c.bg_alt, bg = c.bg_alt })
hl("BufferLineTruncMarker", { fg = c.fg_dim, bg = c.bg_alt })
hl("BufferLineNumbers", { fg = c.fg_dim, bg = c.bg_alt })
hl("BufferLineNumbersSelected", { fg = c.fg, bg = c.bg, bold = true })
hl("BufferLineDiagnostic", { fg = c.fg_dark, bg = c.bg_alt })
hl("BufferLineDiagnosticVisible", { fg = c.fg_dark, bg = c.bg_alt })
hl("BufferLineDiagnosticSelected", { fg = c.fg_dim, bg = c.bg, bold = true })
hl("BufferLineHint", { fg = c.cyan, bg = c.bg_alt })
hl("BufferLineHintVisible", { fg = c.cyan, bg = c.bg_alt })
hl("BufferLineHintSelected", { fg = c.cyan, bg = c.bg, bold = true })
hl("BufferLineHintDiagnostic", { fg = c.cyan, bg = c.bg_alt })
hl("BufferLineHintDiagnosticVisible", { fg = c.cyan, bg = c.bg_alt })
hl("BufferLineHintDiagnosticSelected", { fg = c.cyan, bg = c.bg, bold = true })
hl("BufferLineInfo", { fg = c.blue, bg = c.bg_alt })
hl("BufferLineInfoVisible", { fg = c.blue, bg = c.bg_alt })
hl("BufferLineInfoSelected", { fg = c.blue, bg = c.bg, bold = true })
hl("BufferLineInfoDiagnostic", { fg = c.blue, bg = c.bg_alt })
hl("BufferLineInfoDiagnosticVisible", { fg = c.blue, bg = c.bg_alt })
hl("BufferLineInfoDiagnosticSelected", { fg = c.blue, bg = c.bg, bold = true })
hl("BufferLineWarning", { fg = c.yellow, bg = c.bg_alt })
hl("BufferLineWarningVisible", { fg = c.yellow, bg = c.bg_alt })
hl("BufferLineWarningSelected", { fg = c.yellow, bg = c.bg, bold = true })
hl("BufferLineWarningDiagnostic", { fg = c.yellow, bg = c.bg_alt })
hl("BufferLineWarningDiagnosticVisible", { fg = c.yellow, bg = c.bg_alt })
hl("BufferLineWarningDiagnosticSelected", { fg = c.yellow, bg = c.bg, bold = true })
hl("BufferLineError", { fg = c.red, bg = c.bg_alt })
hl("BufferLineErrorVisible", { fg = c.red, bg = c.bg_alt })
hl("BufferLineErrorSelected", { fg = c.red, bg = c.bg, bold = true })
hl("BufferLineErrorDiagnostic", { fg = c.red, bg = c.bg_alt })
hl("BufferLineErrorDiagnosticVisible", { fg = c.red, bg = c.bg_alt })
hl("BufferLineErrorDiagnosticSelected", { fg = c.red, bg = c.bg, bold = true })

-- Notify
hl("NotifyBackground", { bg = c.bg })
hl("NotifyERRORBorder", { fg = c.red, bg = c.bg })
hl("NotifyWARNBorder", { fg = c.yellow, bg = c.bg })
hl("NotifyINFOBorder", { fg = c.green, bg = c.bg })
hl("NotifyDEBUGBorder", { fg = c.fg_dim, bg = c.bg })
hl("NotifyTRACEBorder", { fg = c.purple, bg = c.bg })
hl("NotifyERRORIcon", { fg = c.red })
hl("NotifyWARNIcon", { fg = c.yellow })
hl("NotifyINFOIcon", { fg = c.green })
hl("NotifyDEBUGIcon", { fg = c.fg_dim })
hl("NotifyTRACEIcon", { fg = c.purple })
hl("NotifyERRORTitle", { fg = c.red, bold = true })
hl("NotifyWARNTitle", { fg = c.yellow, bold = true })
hl("NotifyINFOTitle", { fg = c.green, bold = true })
hl("NotifyDEBUGTitle", { fg = c.fg_dim, bold = true })
hl("NotifyTRACETitle", { fg = c.purple, bold = true })
hl("NotifyERRORBody", { fg = c.fg })
hl("NotifyWARNBody", { fg = c.fg })
hl("NotifyINFOBody", { fg = c.fg })
hl("NotifyDEBUGBody", { fg = c.fg })
hl("NotifyTRACEBody", { fg = c.fg })

-- Noice
hl("NoiceCmdlinePopup", { fg = c.fg, bg = c.bg_alt })
hl("NoiceCmdlinePopupBorder", { fg = c.green, bg = c.bg_alt })
hl("NoiceCmdlinePopupTitle", { fg = c.green, bg = c.bg_alt, bold = true })
hl("NoiceCmdlineIcon", { fg = c.green })
hl("NoiceCmdlineIconSearch", { fg = c.yellow })
hl("NoiceCmdlinePrompt", { fg = c.green })
hl("NoicePopupmenu", { fg = c.fg, bg = c.bg_alt })
hl("NoicePopupmenuBorder", { fg = c.green, bg = c.bg_alt })
hl("NoicePopupmenuSelected", { fg = c.bg, bg = c.green })
hl("NoicePopupmenuMatch", { fg = c.green, bold = true })
hl("NoiceFormatLevelError", { fg = c.red })
hl("NoiceFormatLevelWarn", { fg = c.yellow })
hl("NoiceFormatLevelInfo", { fg = c.green })
hl("NoiceFormatLevelDebug", { fg = c.fg_dim })
hl("NoiceFormatLevelTrace", { fg = c.purple })
hl("NoiceFormatProgressDone", { fg = c.bg, bg = c.green })
hl("NoiceFormatProgressTodo", { fg = c.fg, bg = c.bg_alt })
hl("NoiceFormatEvent", { fg = c.green })
hl("NoiceFormatKind", { fg = c.purple })
hl("NoiceFormatTitle", { fg = c.green, bold = true })
hl("NoiceFormatDate", { fg = c.blue })
hl("NoiceConfirm", { fg = c.fg, bg = c.bg_alt })
hl("NoiceConfirmBorder", { fg = c.green, bg = c.bg_alt })
hl("NoiceSplit", { fg = c.fg, bg = c.bg })
hl("NoiceSplitBorder", { fg = c.fg_dark, bg = c.bg })
hl("NoiceVirtualText", { fg = c.fg_dim })

-- Dashboard / Alpha
hl("DashboardHeader", { fg = c.green, bold = true })
hl("DashboardFooter", { fg = c.fg_dim })
hl("DashboardShortcut", { fg = c.blue })
hl("DashboardShortcutIcon", { fg = c.green })
hl("DashboardCenter", { fg = c.fg })
hl("DashboardProjectTitle", { fg = c.green, bold = true })
hl("DashboardProjectTitleIcon", { fg = c.green })
hl("DashboardProjectIcon", { fg = c.blue })
hl("DashboardMruTitle", { fg = c.green, bold = true })
hl("DashboardMruIcon", { fg = c.blue })
hl("DashboardFiles", { fg = c.fg })
hl("DashboardHyperIcon", { fg = c.purple })
hl("AlphaHeader", { fg = c.green, bold = true })
hl("AlphaFooter", { fg = c.fg_dim })
hl("AlphaShortcut", { fg = c.blue })
hl("AlphaButtons", { fg = c.fg })
hl("AlphaButton", { fg = c.fg })
hl("AlphaButtonShortcut", { fg = c.blue, bold = true })

-- Hop / Leap / Flash
hl("HopNextKey", { fg = c.bg, bg = c.green, bold = true })
hl("HopNextKey1", { fg = c.bg, bg = c.green, bold = true })
hl("HopNextKey2", { fg = c.bg, bg = c.yellow, bold = true })
hl("HopUnmatched", { fg = c.fg_dark })
hl("LeapMatch", { fg = c.bg, bg = c.green, bold = true })
hl("LeapLabelPrimary", { fg = c.bg, bg = c.green, bold = true })
hl("LeapLabelSecondary", { fg = c.bg, bg = c.yellow, bold = true })
hl("LeapLabelSelected", { fg = c.bg, bg = c.purple, bold = true })
hl("LeapBackdrop", { fg = c.fg_dark })
hl("FlashMatch", { fg = c.bg, bg = c.green })
hl("FlashLabel", { fg = c.bg, bg = c.red, bold = true })
hl("FlashBackdrop", { fg = c.fg_dark })
hl("FlashCursor", { fg = c.bg, bg = c.green })

-- Tmux? (not relevant for nvim but common)
hl("TmuxNormal", { fg = c.fg, bg = c.bg })
hl("TmuxWinActive", { fg = c.green, bg = c.bg_alt })
hl("TmuxWinInactive", { fg = c.fg_dim, bg = c.bg_alt })

-- Mason
hl("MasonNormal", { fg = c.fg, bg = c.bg_alt })
hl("MasonHeader", { fg = c.bg, bg = c.green, bold = true })
hl("MasonHeaderSecondary", { fg = c.bg, bg = c.blue, bold = true })
hl("MasonHighlight", { fg = c.green })
hl("MasonHighlightBlock", { fg = c.bg, bg = c.green })
hl("MasonHighlightBlockBold", { fg = c.bg, bg = c.green, bold = true })
hl("MasonMuted", { fg = c.fg_dim })
hl("MasonMutedBlock", { fg = c.fg, bg = c.bg_alt })
hl("MasonMutedBlockBold", { fg = c.fg, bg = c.bg_alt, bold = true })
hl("MasonError", { fg = c.red })
hl("MasonWarning", { fg = c.yellow })

-- Lazy
hl("LazyButton", { fg = c.fg, bg = c.bg_alt })
hl("LazyButtonActive", { fg = c.bg, bg = c.green, bold = true })
hl("LazyComment", { fg = c.fg_dark, italic = true })
hl("LazyCommit", { fg = c.green })
hl("LazyCommitIssue", { fg = c.red })
hl("LazyCommitScope", { fg = c.yellow })
hl("LazyCommitType", { fg = c.purple })
hl("LazyDir", { fg = c.blue })
hl("LazyH1", { fg = c.bg, bg = c.green, bold = true })
hl("LazyH2", { fg = c.green, bold = true })
hl("LazyLocal", { fg = c.blue })
hl("LazyProgressDone", { fg = c.green })
hl("LazyProgressTodo", { fg = c.fg_dark })
hl("LazyProp", { fg = c.yellow })
hl("LazyReasonCmd", { fg = c.purple })
hl("LazyReasonEvent", { fg = c.purple })
hl("LazyReasonFt", { fg = c.blue })
hl("LazyReasonImport", { fg = c.yellow })
hl("LazyReasonKeys", { fg = c.green })
hl("LazyReasonPlugin", { fg = c.blue })
hl("LazyReasonRuntime", { fg = c.purple })
hl("LazyReasonSource", { fg = c.cyan })
hl("LazyReasonStart", { fg = c.green })
hl("LazyTaskError", { fg = c.red })
hl("LazyTaskOutput", { fg = c.fg })
hl("LazyUrl", { fg = c.blue, underline = true })
hl("LazyValue", { fg = c.orange })
hl("LazyVersion", { fg = c.green })
hl("LazyButtonHover", { fg = c.fg, bg = c.bg_sel })

-- Misc
hl("helpExample", { fg = c.green })
hl("helpCommand", { fg = c.green, bold = true })
hl("helpHyperTextJump", { fg = c.blue, underline = true })
hl("helpSpecial", { fg = c.cyan })
hl("helpHeader", { fg = c.green, bold = true })
hl("helpSectionDelim", { fg = c.fg_dark })
hl("helpOption", { fg = c.blue })
hl("helpNote", { fg = c.yellow, bold = true })
hl("helpWarning", { fg = c.yellow })
hl("helpDeprecated", { fg = c.red, strikethrough = true })
hl("helpUnidentified", { fg = c.fg_dim })
hl("helpVim", { fg = c.green })
hl("helpAttr", { fg = c.cyan })
hl("helpType", { fg = c.yellow })
hl("helpFuncName", { fg = c.blue })
hl("helpTitle", { fg = c.green, bold = true })

-- Invisible characters
hl("IndentLine", { fg = c.bg_alt })
hl("IndentLineCurrent", { fg = c.fg_dark })

-- Rainbow delimiters
hl("RainbowDelimiterRed", { fg = c.red })
hl("RainbowDelimiterYellow", { fg = c.yellow })
hl("RainbowDelimiterBlue", { fg = c.blue })
hl("RainbowDelimiterOrange", { fg = c.orange })
hl("RainbowDelimiterGreen", { fg = c.green })
hl("RainbowDelimiterViolet", { fg = c.purple })
hl("RainbowDelimiterCyan", { fg = c.cyan })

-- Symbols outline
hl("SymbolsOutlineConnector", { fg = c.fg_dark })
hl("SymbolsOutlineFoldMarker", { fg = c.fg_dim })
hl("SymbolsOutlineRoot", { fg = c.green, bold = true })

-- Aerial
hl("AerialLine", { bg = c.bg_sel })
hl("AerialGuide", { fg = c.fg_dark })
hl("AerialBooleanIcon", { fg = c.orange })
hl("AerialClassIcon", { fg = c.yellow })
hl("AerialConstantIcon", { fg = c.orange })
hl("AerialConstructorIcon", { fg = c.yellow })
hl("AerialEnumIcon", { fg = c.yellow })
hl("AerialEnumMemberIcon", { fg = c.orange })
hl("AerialEventIcon", { fg = c.purple })
hl("AerialFieldIcon", { fg = c.cyan })
hl("AerialFileIcon", { fg = c.blue })
hl("AerialFunctionIcon", { fg = c.blue })
hl("AerialInterfaceIcon", { fg = c.yellow })
hl("AerialKeyIcon", { fg = c.purple })
hl("AerialMethodIcon", { fg = c.blue })
hl("AerialModuleIcon", { fg = c.yellow })
hl("AerialNamespaceIcon", { fg = c.yellow })
hl("AerialNullIcon", { fg = c.red })
hl("AerialNumberIcon", { fg = c.orange })
hl("AerialObjectIcon", { fg = c.yellow })
hl("AerialOperatorIcon", { fg = c.purple })
hl("AerialPackageIcon", { fg = c.yellow })
hl("AerialPropertyIcon", { fg = c.cyan })
hl("AerialStringIcon", { fg = c.green })
hl("AerialStructIcon", { fg = c.yellow })
hl("AerialTypeParameterIcon", { fg = c.yellow })
hl("AerialVariableIcon", { fg = c.fg })

-- Navic / Navbuddy
hl("NavicIconsFile", { fg = c.blue })
hl("NavicIconsModule", { fg = c.yellow })
hl("NavicIconsNamespace", { fg = c.yellow })
hl("NavicIconsPackage", { fg = c.yellow })
hl("NavicIconsClass", { fg = c.yellow })
hl("NavicIconsMethod", { fg = c.blue })
hl("NavicIconsProperty", { fg = c.cyan })
hl("NavicIconsField", { fg = c.cyan })
hl("NavicIconsConstructor", { fg = c.yellow })
hl("NavicIconsEnum", { fg = c.yellow })
hl("NavicIconsInterface", { fg = c.yellow })
hl("NavicIconsFunction", { fg = c.blue })
hl("NavicIconsVariable", { fg = c.fg })
hl("NavicIconsConstant", { fg = c.orange })
hl("NavicIconsString", { fg = c.green })
hl("NavicIconsNumber", { fg = c.orange })
hl("NavicIconsBoolean", { fg = c.orange })
hl("NavicIconsArray", { fg = c.yellow })
hl("NavicIconsObject", { fg = c.yellow })
hl("NavicIconsKey", { fg = c.purple })
hl("NavicIconsNull", { fg = c.red })
hl("NavicIconsEnumMember", { fg = c.orange })
hl("NavicIconsStruct", { fg = c.yellow })
hl("NavicIconsEvent", { fg = c.purple })
hl("NavicIconsOperator", { fg = c.purple })
hl("NavicIconsTypeParameter", { fg = c.yellow })
hl("NavicText", { fg = c.fg_dim })
hl("NavicSeparator", { fg = c.fg_dark })

-- Bqf / quickfix
hl("BqfPreviewBorder", { fg = c.green, bg = c.bg_alt })
hl("BqfPreviewTitle", { fg = c.bg, bg = c.green, bold = true })
hl("BqfPreviewRange", { bg = c.bg_sel })
hl("BqfPreviewCursor", { fg = c.bg, bg = c.green })
hl("BqfPreviewCursorLine", { bg = c.bg_alt })
hl("BqfSign", { fg = c.green })
hl("QuickFixLine", { bg = c.bg_sel })
hl("qfFileName", { fg = c.blue })
hl("qfLineNr", { fg = c.fg_dim })
hl("qfError", { fg = c.red })
hl("qfWarning", { fg = c.yellow })

-- Trouble
hl("TroubleText", { fg = c.fg })
hl("TroubleCount", { fg = c.bg, bg = c.fg_dim })
hl("TroubleNormal", { fg = c.fg, bg = c.bg })
hl("TroubleLocation", { fg = c.fg_dim })
hl("TroubleFoldIcon", { fg = c.fg_dim })
hl("TroubleIndent", { fg = c.bg_alt })
hl("TroubleCode", { fg = c.fg_dim })
hl("TroubleSource", { fg = c.fg_dim })
hl("TroubleSignError", { fg = c.red })
hl("TroubleSignWarning", { fg = c.yellow })
hl("TroubleSignInformation", { fg = c.blue })
hl("TroubleSignHint", { fg = c.cyan })
hl("TroubleSignOther", { fg = c.fg_dim })
hl("TroubleError", { fg = c.red })
hl("TroubleWarning", { fg = c.yellow })
hl("TroubleInformation", { fg = c.blue })
hl("TroubleHint", { fg = c.cyan })
hl("TroubleOther", { fg = c.fg_dim })

-- nvim-ufo
hl("UfoFoldedBg", { bg = c.bg_alt })
hl("UfoFoldedFg", { fg = c.fg_dim })
hl("UfoPreviewSbar", { bg = c.bg_alt })
hl("UfoPreviewThumb", { bg = c.fg_dim })
hl("UfoPreviewWinBar", { fg = c.green, bg = c.bg_alt })
hl("UfoFoldedEllipsis", { fg = c.fg_dim })
hl("UfoCursorFoldedLine", { bg = c.bg_sel })

-- CodeCompanion / Avante
hl("CodeCompanionChatHeader", { fg = c.green, bold = true })
hl("CodeCompanionChatSeparator", { fg = c.fg_dark })
hl("CodeCompanionChatTool", { fg = c.blue })
hl("CodeCompanionChatVariable", { fg = c.orange })
hl("CodeCompanionChatAssistant", { fg = c.green })
hl("CodeCompanionChatUser", { fg = c.blue })
hl("AvanteTitle", { fg = c.bg, bg = c.green, bold = true })
hl("AvanteSubtitle", { fg = c.bg, bg = c.blue, bold = true })
hl("AvanteThirdTitle", { fg = c.bg, bg = c.purple, bold = true })
hl("AvanteReversedTitle", { fg = c.green })
hl("AvanteReversedSubtitle", { fg = c.blue })
hl("AvanteReversedThirdTitle", { fg = c.purple })
hl("AvanteHint", { fg = c.green })
hl("AvanteAnnotation", { fg = c.fg_dim })
hl("AvanteSuggestion", { fg = c.fg_dim })

-- DAP
hl("DapBreakpoint", { fg = c.red })
hl("DapBreakpointCondition", { fg = c.yellow })
hl("DapBreakpointRejected", { fg = c.orange })
hl("DapLogPoint", { fg = c.blue })
hl("DapStopped", { fg = c.green })
hl("DapStoppedLine", { bg = c.bg_sel })
hl("DapUIFrameName", { fg = c.fg })
hl("DapUIScope", { fg = c.green, bold = true })
hl("DapUIType", { fg = c.yellow })
hl("DapUIValue", { fg = c.fg })
hl("DapUIVariable", { fg = c.fg })
hl("DapUIModifiedValue", { fg = c.orange, bold = true })
hl("DapUIDecoration", { fg = c.green })
hl("DapUIThread", { fg = c.green })
hl("DapUIStoppedThread", { fg = c.red })
hl("DapUIFrameName", { fg = c.fg })
hl("DapUISource", { fg = c.cyan })
hl("DapUILineNumber", { fg = c.green })
hl("DapUIFloatBorder", { fg = c.green, bg = c.bg_alt })
hl("DapUIWatchesEmpty", { fg = c.red })
hl("DapUIWatchesValue", { fg = c.green })
hl("DapUIWatchesError", { fg = c.red })
hl("DapUIBreakpointsPath", { fg = c.green })
hl("DapUIBreakpointsInfo", { fg = c.green })
hl("DapUIBreakpointsCurrentLine", { fg = c.green, bold = true })
hl("DapUIBreakpointsLine", { fg = c.fg })
hl("DapUIBreakpointsDisabledLine", { fg = c.fg_dark })
hl("DapUIStepOver", { fg = c.green })
hl("DapUIStepInto", { fg = c.green })
hl("DapUIStepBack", { fg = c.green })
hl("DapUIStepOut", { fg = c.green })
hl("DapUIStop", { fg = c.red })
hl("DapUIPlayPause", { fg = c.green })
hl("DapUIRestart", { fg = c.green })
hl("DapUIUnavailable", { fg = c.fg_dark })

-- Neotest
hl("NeotestAdapterName", { fg = c.green, bold = true })
hl("NeotestBorder", { fg = c.green, bg = c.bg_alt })
hl("NeotestDir", { fg = c.blue })
hl("NeotestExpandMarker", { fg = c.fg_dim })
hl("NeotestFailed", { fg = c.red })
hl("NeotestFile", { fg = c.blue })
hl("NeotestFocused", { fg = c.green, bold = true })
hl("NeotestIndent", { fg = c.bg_alt })
hl("NeotestMarked", { fg = c.yellow, bold = true })
hl("NeotestNamespace", { fg = c.yellow })
hl("NeotestPassed", { fg = c.green })
hl("NeotestRunning", { fg = c.yellow })
hl("NeotestSkipped", { fg = c.fg_dim })
hl("NeotestTarget", { fg = c.green })
hl("NeotestTest", { fg = c.fg })
hl("NeotestUnknown", { fg = c.fg_dim })
hl("NeotestWatching", { fg = c.yellow })
hl("NeotestWinSelect", { fg = c.green, bold = true })

-- Neogit
hl("NeogitBranch", { fg = c.green, bold = true })
hl("NeogitBranchHead", { fg = c.green, bold = true })
hl("NeogitRemote", { fg = c.purple, bold = true })
hl("NeogitObjectId", { fg = c.fg_dim })
hl("NeogitStash", { fg = c.blue })
hl("NeogitRebaseDone", { fg = c.green })
hl("NeogitRebasing", { fg = c.yellow })
hl("NeogitChangeAdded", { fg = c.green })
hl("NeogitChangeModified", { fg = c.yellow })
hl("NeogitChangeDeleted", { fg = c.red })
hl("NeogitChangeRenamed", { fg = c.blue })
hl("NeogitChangeUpdated", { fg = c.yellow })
hl("NeogitChangeCopied", { fg = c.cyan })
hl("NeogitChangeUnmerged", { fg = c.orange })
hl("NeogitChangeUntracked", { fg = c.fg_dim })
hl("NeogitChangeNewFile", { fg = c.green })
hl("NeogitDiffAdd", { fg = c.green, bg = c.bg })
hl("NeogitDiffAddHighlight", { fg = c.green, bg = c.bg_alt })
hl("NeogitDiffDelete", { fg = c.red, bg = c.bg })
hl("NeogitDiffDeleteHighlight", { fg = c.red, bg = c.bg_alt })
hl("NeogitDiffContext", { fg = c.fg, bg = c.bg })
hl("NeogitDiffContextHighlight", { fg = c.fg, bg = c.bg_alt })
hl("NeogitDiffHeader", { fg = c.fg, bg = c.bg_alt, bold = true })
hl("NeogitDiffHeaderHighlight", { fg = c.green, bg = c.bg_alt, bold = true })
hl("NeogitHunkHeader", { fg = c.fg, bg = c.bg_alt })
hl("NeogitHunkHeaderHighlight", { fg = c.green, bg = c.bg_alt })
hl("NeogitFold", { fg = c.fg_dim })
hl("NeogitCommitViewHeader", { fg = c.bg, bg = c.green, bold = true })
hl("NeogitNotificationError", { fg = c.red })
hl("NeogitNotificationInfo", { fg = c.green })
hl("NeogitNotificationWarning", { fg = c.yellow })

-- Diffview
hl("DiffviewNormal", { fg = c.fg, bg = c.bg })
hl("DiffviewStatusLine", { fg = c.fg, bg = c.bg_alt })
hl("DiffviewFilePanelTitle", { fg = c.green, bold = true })
hl("DiffviewFilePanelCounter", { fg = c.fg, bg = c.bg_alt })
hl("DiffviewFilePanelFileName", { fg = c.fg })
hl("DiffviewFilePanelPath", { fg = c.fg_dim })
hl("DiffviewFilePanelInsertions", { fg = c.green })
hl("DiffviewFilePanelDeletions", { fg = c.red })
hl("DiffviewFilePanelRootPath", { fg = c.green, bold = true })
hl("DiffviewFilePanelSelected", { fg = c.green })
hl("DiffviewFilePanelTitle", { fg = c.green, bold = true })
hl("DiffviewFilePanelCounter", { fg = c.fg })
hl("DiffviewDiffAdd", { fg = c.green, bg = c.bg })
hl("DiffviewDiffChange", { fg = c.yellow, bg = c.bg })
hl("DiffviewDiffDelete", { fg = c.red, bg = c.bg })
hl("DiffviewDiffText", { fg = c.bg, bg = c.yellow })

-- Glance
hl("GlancePreviewNormal", { fg = c.fg, bg = c.bg })
hl("GlancePreviewMatch", { fg = c.bg, bg = c.green, bold = true })
hl("GlancePreviewCursorLine", { bg = c.bg_alt })
hl("GlancePreviewBorderTop", { fg = c.green, bg = c.bg_alt })
hl("GlanceListNormal", { fg = c.fg, bg = c.bg_alt })
hl("GlanceListMatch", { fg = c.green, bold = true })
hl("GlanceListCursorLine", { bg = c.bg_sel })
hl("GlanceListBorderTop", { fg = c.green, bg = c.bg_alt })
hl("GlanceListCount", { fg = c.bg, bg = c.green })
hl("GlanceListFilename", { fg = c.blue })
hl("GlanceListLineNumber", { fg = c.fg_dim })
hl("GlanceListBorderBottom", { fg = c.green, bg = c.bg_alt })
hl("GlanceBorderTop", { fg = c.green, bg = c.bg_alt })
hl("GlanceWinBarFilename", { fg = c.fg, bg = c.bg_alt })
hl("GlanceWinBarFilepath", { fg = c.fg_dim, bg = c.bg_alt })
hl("GlanceWinBarTitle", { fg = c.bg, bg = c.green, bold = true })

-- Navbuddy
hl("NavbuddyName", { fg = c.fg, bold = true })
hl("NavbuddyScope", { fg = c.green })
hl("NavbuddyIcon", { fg = c.green })
hl("NavbuddyType", { fg = c.yellow })
hl("NavbuddyFloatBorder", { fg = c.green, bg = c.bg_alt })

-- Tiny inline diagnostic
hl("TinyInlineDiagnosticError", { fg = c.red, bg = c.bg_alt })
hl("TinyInlineDiagnosticWarn", { fg = c.yellow, bg = c.bg_alt })
hl("TinyInlineDiagnosticInfo", { fg = c.blue, bg = c.bg_alt })
hl("TinyInlineDiagnosticHint", { fg = c.cyan, bg = c.bg_alt })

-- Kulala
hl("KulalaCodeBlock", { fg = c.green, bg = c.bg_alt })
hl("KulalaMethod", { fg = c.green, bold = true })
hl("KulalaUrl", { fg = c.blue, underline = true })
hl("KulalaHeader", { fg = c.purple })
hl("KulalaVariable", { fg = c.orange })
hl("KulalaStatus", { fg = c.green })

-- Gitsigns blame
hl("GitSignsBlameLine", { fg = c.fg_dark, bg = c.bg_alt })

-- Barbecue
hl("BarbecueNormal", { fg = c.fg_dim, bg = c.bg_alt })
hl("BarbecueContext", { fg = c.fg_dim, bg = c.bg_alt })
hl("BarbecueContextClass", { fg = c.yellow, bg = c.bg_alt })
hl("BarbecueContextFunction", { fg = c.blue, bg = c.bg_alt })
hl("BarbecueContextMethod", { fg = c.blue, bg = c.bg_alt })
hl("BarbecueContextStruct", { fg = c.yellow, bg = c.bg_alt })
hl("BarbecueContextEnum", { fg = c.yellow, bg = c.bg_alt })
hl("BarbecueContextNamespace", { fg = c.yellow, bg = c.bg_alt })
hl("BarbecueContextInterface", { fg = c.yellow, bg = c.bg_alt })
hl("BarbecueContextModule", { fg = c.yellow, bg = c.bg_alt })
hl("BarbecueContextType", { fg = c.yellow, bg = c.bg_alt })
hl("BarbecueContextVariable", { fg = c.fg, bg = c.bg_alt })
hl("BarbecueContextConstant", { fg = c.orange, bg = c.bg_alt })
hl("BarbecueContextProperty", { fg = c.cyan, bg = c.bg_alt })
hl("BarbecueContextField", { fg = c.cyan, bg = c.bg_alt })
hl("BarbecueContextEnumMember", { fg = c.orange, bg = c.bg_alt })
hl("BarbecueContextConstructor", { fg = c.yellow, bg = c.bg_alt })
hl("BarbecueSeparator", { fg = c.fg_dark, bg = c.bg_alt })

-- Dropbar
hl("DropBarCurrentContext", { fg = c.green, bg = c.bg_alt })
hl("DropBarIconCurrentContext", { fg = c.green, bg = c.bg_alt })
hl("DropBarKindCurrent", { fg = c.green, bg = c.bg_alt })
hl("DropBarMenuCurrentContext", { fg = c.green, bg = c.bg_alt })
hl("DropBarMenuHoverEntry", { fg = c.bg, bg = c.green })
hl("DropBarMenuHoverIcon", { fg = c.bg, bg = c.green })
hl("DropBarMenuHoverName", { fg = c.bg, bg = c.green })
hl("DropBarMenuHoverSymbol", { fg = c.bg, bg = c.green })
hl("DropBarPreview", { fg = c.bg, bg = c.green })

-- Scrollbar
hl("ScrollbarHandle", { fg = c.fg_dim, bg = c.bg_alt })
hl("ScrollbarSearchHandle", { fg = c.bg, bg = c.yellow })
hl("ScrollbarErrorHandle", { fg = c.red, bg = c.bg_alt })
hl("ScrollbarWarnHandle", { fg = c.yellow, bg = c.bg_alt })
hl("ScrollbarInfoHandle", { fg = c.blue, bg = c.bg_alt })
hl("ScrollbarHintHandle", { fg = c.cyan, bg = c.bg_alt })
hl("ScrollbarMiscHandle", { fg = c.purple, bg = c.bg_alt })
hl("ScrollbarGitAddHandle", { fg = c.green, bg = c.bg_alt })
hl("ScrollbarGitChangeHandle", { fg = c.yellow, bg = c.bg_alt })
hl("ScrollbarGitDeleteHandle", { fg = c.red, bg = c.bg_alt })

-- Fidget
hl("FidgetTitle", { fg = c.green, bold = true })
hl("FidgetTask", { fg = c.fg })
hl("FidgetDone", { fg = c.green })

-- Overseer
hl("OverseerPENDING", { fg = c.fg_dim })
hl("OverseerRUNNING", { fg = c.yellow })
hl("OverseerSUCCESS", { fg = c.green })
hl("OverseerCANCELED", { fg = c.fg_dim })
hl("OverseerFAILURE", { fg = c.red })
hl("OverseerDISPOSED", { fg = c.fg_dark })

-- Harpoon
hl("HarpoonWindow", { fg = c.fg, bg = c.bg })
hl("HarpoonBorder", { fg = c.green, bg = c.bg })
hl("HarpoonTitle", { fg = c.bg, bg = c.green, bold = true })
hl("HarpoonCurrentFile", { fg = c.green, bold = true })

-- Todo comments
hl("TodoBgFIX", { fg = c.bg, bg = c.red, bold = true })
hl("TodoFgFIX", { fg = c.red })
hl("TodoSignFIX", { fg = c.red })
hl("TodoBgTODO", { fg = c.bg, bg = c.yellow, bold = true })
hl("TodoFgTODO", { fg = c.yellow })
hl("TodoSignTODO", { fg = c.yellow })
hl("TodoBgHACK", { fg = c.bg, bg = c.orange, bold = true })
hl("TodoFgHACK", { fg = c.orange })
hl("TodoSignHACK", { fg = c.orange })
hl("TodoBgWARN", { fg = c.bg, bg = c.yellow, bold = true })
hl("TodoFgWARN", { fg = c.yellow })
hl("TodoSignWARN", { fg = c.yellow })
hl("TodoBgPERF", { fg = c.bg, bg = c.purple, bold = true })
hl("TodoFgPERF", { fg = c.purple })
hl("TodoSignPERF", { fg = c.purple })
hl("TodoBgNOTE", { fg = c.bg, bg = c.blue, bold = true })
hl("TodoFgNOTE", { fg = c.blue })
hl("TodoSignNOTE", { fg = c.blue })
hl("TodoBgTEST", { fg = c.bg, bg = c.green, bold = true })
hl("TodoFgTEST", { fg = c.green })
hl("TodoSignTEST", { fg = c.green })

-- Glance
hl("GlanceWinBarTitle", { fg = c.bg, bg = c.green, bold = true })
hl("GlanceWinBarFileName", { fg = c.fg, bg = c.bg_alt })
hl("GlanceWinBarFilePath", { fg = c.fg_dim, bg = c.bg_alt })
hl("GlanceListBorderTop", { fg = c.green, bg = c.bg_alt })
hl("GlanceListNormal", { fg = c.fg, bg = c.bg_alt })
hl("GlanceListMatch", { fg = c.green, bold = true })
hl("GlanceListCursorLine", { bg = c.bg_sel })
hl("GlanceListCount", { fg = c.bg, bg = c.green })
hl("GlanceListFileName", { fg = c.blue })
hl("GlanceListLineNumber", { fg = c.fg_dim })
hl("GlancePreviewBorderTop", { fg = c.green, bg = c.bg_alt })
hl("GlancePreviewNormal", { fg = c.fg, bg = c.bg })
hl("GlancePreviewMatch", { fg = c.bg, bg = c.green, bold = true })
hl("GlancePreviewCursorLine", { bg = c.bg_alt })

-- Zen mode
hl("ZenBg", { bg = c.bg })

-- Terminal (built-in :terminal)
hl("TermCursor", { fg = c.bg, bg = c.green })
hl("TermCursorNC", { fg = c.fg, bg = c.bg_alt })
hl("TermNormal", { fg = c.fg, bg = c.bg })
hl("TermNormalNC", { fg = c.fg, bg = c.bg })
